Fix parametrize service action in case of content update
The previously used namespace caused issue while generating
consul_service resource

 FATAL: NoMethodError: undefined method `action_on_update' for Custom resource consul_service from cookbook consul

See http://tfitch.com/chef/2014/09/01/sending-name-value-pairs-from-chef-cookbook.html
for detail about how to generate dynamic attributes, which is used here.

Moving to the 'consul' namespace to avoid this error.